# Generated by Django 3.0.7 on 2020-07-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=300)),
                ('domain_description', models.TextField()),
                ('insert_date', models.DateTimeField()),
                ('last_scan_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
