# Generated by Django 2.2.12 on 2020-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=300)),
                ('domain_description', models.TextField()),
                ('insert_date', models.DateTimeField()),
            ],
        ),
    ]
