# Generated by Django 3.1.3 on 2020-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
