# Generated by Django 3.0.6 on 2020-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='last_scan_date',
            field=models.DateTimeField(null=True),
        ),
    ]
