# Generated by Django 3.0.7 on 2020-07-11 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_domain_last_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 8, 40, 9, 559583, tzinfo=utc)),
        ),
    ]
