# Generated by Django 3.0.7 on 2020-07-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0003_auto_20200711_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='insert_date',
            field=models.DateTimeField(),
        ),
    ]
