# Generated by Django 3.0.7 on 2020-07-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0004_auto_20200711_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
