FROM node:22-slim

WORKDIR /app

COPY VERSION ./VERSION

COPY frontend/package*.json ./

RUN npm install

COPY frontend/. .

RUN node scripts/fetch-tech-icons.mjs

EXPOSE 5173

CMD ["npm", "run", "dev"]
