.PHONY: help up down build logs logs-api logs-worker lint lint-python lint-frontend check-lists \
        test test-python test-frontend migrate migrate-create migrate-draft \
        migrate-history migrate-downgrade db-stamp db-reset shell-api shell-worker db-shell

# The one list of Python packages. CI runs the targets below rather than its own
# copy; the copies other tools need (pre-commit, compose, the Dockerfiles, the
# api entrypoint) are compared with it by `make check-lists`.
PACKAGES = api shared reports worker stages tools toolbox interest mcp channels connectors tests

# ruff at the version pyproject.toml's dev group pins, which pre-commit also runs
RUFF_VERSION := $(shell sed -n 's/^ *"ruff==\([^"]*\)".*/\1/p' pyproject.toml)
RUFF = uvx ruff@$(RUFF_VERSION)

help:
	@echo "reNgine 3.0 Dev Commands"
	@echo ""
	@echo "  Docker:"
	@echo "    make up              Start all services"
	@echo "    make down            Stop all services"
	@echo "    make build           Rebuild all containers"
	@echo "    make logs            Tail all logs"
	@echo "    make logs-api        Tail API logs"
	@echo "    make logs-worker     Tail worker logs"
	@echo ""
	@echo "  Checks:"
	@echo "    make lint            lint-python, then lint-frontend"
	@echo "    make lint-python     package lists, then pinned ruff check and format"
	@echo "    make lint-frontend   prettier and eslint"
	@echo "    make test            test-python, then test-frontend"
	@echo "    make test-python     pytest in a one-off api container (db must be up)"
	@echo "    make test-frontend   svelte-check and vitest"
	@echo ""
	@echo "  Database Migrations:"
	@echo "    make migrate                  Apply all pending migrations"
	@echo "    make migrate-create m=msg     Empty revision to hand-write"
	@echo "    make migrate-draft  m=msg     Autogenerated draft to edit down"
	@echo "    make migrate-history          Show migration history"
	@echo "    make migrate-downgrade        Rollback last migration"
	@echo "    make db-stamp                 Stamp DB as current (existing DB setup)"
	@echo "    make db-reset                 Drop all tables and re-migrate (DESTRUCTIVE)"
	@echo ""
	@echo "  Debug:"
	@echo "    make shell-api       Shell into API container"
	@echo "    make shell-worker    Shell into worker container"
	@echo "    make db-shell        PostgreSQL shell"

# Docker
up:
	docker compose up -d

down:
	docker compose down

build:
	docker compose build

logs:
	docker compose logs -f

logs-api:
	docker compose logs -f api

logs-worker:
	docker compose logs -f worker-default

# Checks: CI runs these same targets
lint: lint-python lint-frontend

lint-python: check-lists
	@test -n "$(RUFF_VERSION)" || { echo "pyproject.toml pins no ruff version"; exit 1; }
	$(RUFF) check $(PACKAGES) .github/scripts
	$(RUFF) format --check $(PACKAGES) .github/scripts

lint-frontend:
	cd frontend && npm run lint

check-lists:
	python3 .github/scripts/check_lists.py --ruff "$(RUFF_VERSION)" $(PACKAGES)

test: test-python test-frontend

# a one-off container from the api service: the stack's mounts and .env, the
# running db and redis, and no dependence on the api container being up
test-python:
	docker compose run --rm --no-deps api /app/.venv/bin/python -m pytest tests --tb=short

test-frontend:
	cd frontend && npm run check && npm run test

migrate:
	docker compose exec api uv run alembic upgrade head

migrate-create:
	@if [ -z "$(m)" ]; then echo "Usage: make migrate-create m='migration message'"; exit 1; fi
	docker compose exec api uv run alembic revision -m "$(m)"

migrate-draft:
	@if [ -z "$(m)" ]; then echo "Usage: make migrate-draft m='migration message'"; exit 1; fi
	docker compose exec api uv run alembic revision --autogenerate -m "$(m)"

migrate-history:
	docker compose exec api uv run alembic history --verbose

migrate-downgrade:
	docker compose exec api uv run alembic downgrade -1

db-stamp:
	docker compose exec api uv run alembic stamp head

db-reset:
	@echo "Every table is dropped and the migrations are re-applied."
	@read -p "Continue? [y/N] " confirm && [ "$$confirm" = "y" ] || exit 1
	docker compose exec api uv run alembic downgrade base
	docker compose exec api uv run alembic upgrade head

# Shells
shell-api:
	docker compose exec api bash

shell-worker:
	docker compose exec worker-default bash

db-shell:
	docker compose exec db sh -c 'psql -U "$${POSTGRES_USER:-rengine}" -d "$${POSTGRES_DB:-rengine}"'
