# Global vars for all tools
#
# custom_headers: ['User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.71 Safari/537.36']     # FFUF, Nuclei, Dalfox, CRL Fuzz, HTTP Crawl, Fetch URL, etc
enable_http_crawl: true           # All tools
timeout: 10                       # Subdomain discovery, Screenshot, Port scan, FFUF, Nuclei
threads: 10                       # All tools
rate_limit: 20                   # Port scan, FFUF, Nuclei
# intensity: 'normal'               # Screenshot (grab only the root endpoints of each subdomain), Nuclei (reduce number of endpoints to scan), OSINT (not implemented yet)
# retries: 1                        # Nuclei

subdomain_discovery: {
  # 不要使用oneallfor，会跑崩网卡
  'uses_tools': ['subfinder', 'tlsx'],  # amass-passive, amass-active, All
  'enable_http_crawl': true,
  'threads': 10,
  'timeout': 5,
  # 'use_subfinder_config': false,
  # 'use_amass_config': false,
  # 'amass_wordlist': 'deepmagic.com-prefixes-top50000'
}
http_crawl: {
  # 'threads': 30,
  # 'follow_redirect': true
}
# port_scan: {
#   'enable_http_crawl': true,
#   'timeout': 5,
#   # 'exclude_ports': [],
#   # 'exclude_subdomains': [],
#   'ports': ['top-100'],
#   'rate_limit': 30,
#   'threads': 30,
#   'passive': false,
#   # 'use_naabu_config': false,
#   # 'enable_nmap': true,
#   # 'nmap_cmd': '',
#   # 'nmap_script': '',
#   # 'nmap_script_args': ''
# }
#osint: {
#  'discover': [
#      'emails',
#      'metainfo',
#      'employees'
#    ],
#  'dorks': [
#    'login_pages',
#    'admin_panels',
#    'dashboard_pages',
#    'stackoverflow',
#    'social_media',
#    'project_management',
#    'code_sharing',
#    'config_files',
#    'jenkins',
#    'wordpress_files',
#    'php_error',
#    'exposed_documents',
#    'db_files',
#    'git_exposed'
#  ],
#  # 'custom_dorks': [],
#  'intensity': 'normal',
#  'documents_limit': 50
#}
dir_file_fuzz: {
  'auto_calibration': true,
  'enable_http_crawl': true,
  'rate_limit': 30,
  'extensions': ['bak','txt','sql','zip','rar','7z','tar','tar.gz'],
  'follow_redirect': false,
  'max_time': 0,
  'match_http_status': [200, 204],
  'recursive_level': 2,
  'stop_on_error': false,
  'timeout': 5,
  'threads': 20,
  'wordlist_name': 'dirsearch'
}
fetch_url: {
  'uses_tools': ['katana', 'gau'],
  'remove_duplicate_endpoints': true,
  'duplicate_fields': ['content_length', 'page_title'],
  'enable_http_crawl': true,
  'gf_patterns': ['interestingparams'],
#  'ignore_file_extensions': ['png', 'jpg', 'jpeg', 'gif', 'mp4', 'mpeg', 'mp3'],
  'ignore_file_extensions': [
    'png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'webp',  # 图像文件
    'mp4', 'mpeg', 'mp3', 'avi', 'wmv', 'mov', 'flv', 'mkv', 'webm', 'ogg',  # 视频与音频文件
    'css', 'scss', 'less',  # 样式表文件
    'js', 'jsx', 'ts', 'tsx',  # 脚本文件
    'ttf', 'woff', 'woff2', 'eot', 'otf',  # 字体文件
    'svg', 'ico', 'eps', 'dxf',  # 矢量图与图标
#    'zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'xz',  # 压缩文件
    'pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'rtf', 'txt',  # 文档文件
    'log', 'bak', 'tmp',  # 日志与临时文件
    'dll', 'exe', 'so', 'bin', 'dat',  # 可执行与二进制文件
    'swf', 'fla',  # Flash 文件
    'iso', 'img', 'dmg', 'vmdk',  # 磁盘映像文件
#    'cfg', 'ini', 'yaml', 'yml', 'json', 'xml',  # 配置文件
#    'db', 'sql', 'sqlite', 'db3',  # 数据库文件
    'crt', 'pem', 'key',  # 证书文件
    'psd', 'ai', 'xd', 'sketch', 'indd', 'fig',  # 设计文件
  ],
  'threads': 20,
  # 'exclude_subdomains': false
}
vulnerability_scan: {
  'run_nuclei': true,
  'run_dalfox': false,
  'run_crlfuzz': false,
  'run_s3scanner': false,
  'enable_http_crawl': true,
  'concurrency': 20,
  'intensity': 'normal',
  'rate_limit': 30,
  'retries': 1,
  'timeout': 5,
  'fetch_gpt_report': true,
  'nuclei': {
    'use_nuclei_config': false,
    'severities': ['medium', 'high', 'critical'],
    # 'tags': [],                 # Nuclei tags (https://github.com/projectdiscovery/nuclei-templates)
    # 'templates': [],            # Nuclei templates (https://github.com/projectdiscovery/nuclei-templates)
    # 'custom_templates': []      # Nuclei custom templates uploaded in reNgine
  }
}
waf_detection: {
  'enable_http_crawl': true
}
#screenshot: {
#  'enable_http_crawl': true,
#  'intensity': 'normal',
#  'timeout': 10,
#  'threads': 40
#}