apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  rengine.conf: |
    server {
        listen 80;
        listen [::]:80;
        server_name rengine.example.com;

        charset utf-8;
        keepalive_timeout 70;

        client_max_body_size 800M;

        location / {
            proxy_read_timeout 300;
            proxy_connect_timeout 300;
            proxy_redirect off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://rengine:8000/;
        }

        location /staticfiles/ {
            alias /usr/src/app/staticfiles/;
        }

        location /protected_media/ {
            internal;
            alias /usr/src/scan_results/;
            autoindex off;
        }
    }