# Generated by Django 3.1.6 on 2021-06-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanEngine', '0001_initial'),
        ('targetApp', '0004_auto_20210607_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_url', models.CharField(max_length=5000)),
                ('content_length', models.IntegerField(default=0)),
                ('page_title', models.CharField(max_length=1000)),
                ('http_status', models.IntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('webserver', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_default', models.BooleanField(blank=True, default=False, null=True)),
                ('matched_gf_patterns', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_scan_date', models.DateTimeField()),
                ('scan_status', models.IntegerField()),
                ('celery_id', models.CharField(blank=True, max_length=100)),
                ('subdomain_discovery', models.BooleanField(default=False, null=True)),
                ('dir_file_search', models.BooleanField(default=False, null=True)),
                ('port_scan', models.BooleanField(default=False, null=True)),
                ('fetch_url', models.BooleanField(default=False, null=True)),
                ('vulnerability_scan', models.BooleanField(default=False, null=True)),
                ('stop_scan_date', models.DateTimeField(null=True)),
                ('used_gf_patterns', models.CharField(blank=True, max_length=500, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('scan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanEngine.enginetype')),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('is_imported_subdomain', models.BooleanField(default=False, null=True)),
                ('http_url', models.CharField(max_length=1000)),
                ('screenshot_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('http_header_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('directory_json', models.JSONField(blank=True, null=True)),
                ('checked', models.BooleanField(blank=True, default=False, null=True)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('cname', models.CharField(blank=True, max_length=1500, null=True)),
                ('http_status', models.IntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('webserver', models.CharField(blank=True, max_length=1000, null=True)),
                ('content_length', models.IntegerField(default=0)),
                ('page_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_cdn', models.BooleanField(default=False)),
                ('ip_addresses', models.ManyToManyField(to='startScan.IP')),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_used', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=400)),
                ('severity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('extracted_results', models.CharField(blank=True, max_length=3000, null=True)),
                ('reference', models.CharField(blank=True, max_length=3000, null=True)),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('http_url', models.CharField(max_length=8000, null=True)),
                ('matcher_name', models.CharField(blank=True, max_length=400, null=True)),
                ('discovered_date', models.DateTimeField(null=True)),
                ('open_status', models.BooleanField(blank=True, default=True, null=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.endpoint')),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
        migrations.AddField(
            model_name='subdomain',
            name='technologies',
            field=models.ManyToManyField(to='startScan.Technology'),
        ),
        migrations.CreateModel(
            name='ScanActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('scan_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_uncommon', models.BooleanField(default=False)),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.ip')),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='scan_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='target_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='technologies',
            field=models.ManyToManyField(to='startScan.IP'),
        ),
    ]
