# Generated by Django 3.2.23 on 2024-09-11 01:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='cfg_excluded_paths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='cfg_imported_subdomains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='cfg_out_of_scope_subdomains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='cfg_starting_point_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
