# Generated by Django 3.2.23 on 2024-08-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_auto_20240821_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanhistory',
            old_name='cfg_starting_point_url',
            new_name='cfg_starting_point_path',
        ),
    ]
