# Generated by Django 3.2.4 on 2021-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_subscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(blank=True, related_name='ip_addresses', to='startScan.IpAddress'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='technologies', to='startScan.Technology'),
        ),
    ]
