# Generated by Django 3.2.23 on 2026-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_auto_20240911_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='exploit_url',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='validation_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('not_working', 'Not Working'), ('patched', 'Patched')], default='unverified', max_length=20),
        ),
    ]
