# Generated by Django 3.2.4 on 2021-10-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_auto_20211019_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='dorks',
            field=models.ManyToManyField(blank=True, related_name='dorks', to='startScan.Dork'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='emails', to='startScan.Email'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employees', to='startScan.Employee'),
        ),
    ]
