# Generated by Django 3.2.4 on 2021-12-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_auto_20211227_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscan',
            old_name='scan_status',
            new_name='status',
        ),
    ]
