# Generated by Django 3.2.23 on 2024-08-22 04:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_rename_cfg_starting_point_url_scanhistory_cfg_starting_point_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='cfg_imported_subdomains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
