# Generated by Django 3.2.4 on 2021-10-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_auto_20211019_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='stop_scan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
