# Generated by Django 3.2.23 on 2026-04-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_auto_20260425_1241'),
        ('startScan', '0003_auto_20260423_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringDiscovery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discovery_type', models.CharField(choices=[('subdomain', 'New Subdomain'), ('ip', 'IP Change'), ('vhost', 'New Virtual Host'), ('directory', 'New Directory'), ('login', 'New Login Page'), ('status_change', 'Status Code Change')], max_length=50)),
                ('content', models.JSONField()),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.scanhistory')),
            ],
        ),
    ]
