# Generated by Django 3.2.4 on 2021-12-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0004_rename_scan_status_subscan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='checked',
        ),
    ]
