# Generated by Django 3.2.4 on 2021-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0004_alter_scanhistory_stop_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(blank=True, null=True, related_name='ip_addresses', to='startScan.IpAddress'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='technologies',
            field=models.ManyToManyField(blank=True, null=True, related_name='technologies', to='startScan.Technology'),
        ),
    ]
