# Generated by Django 3.2.23 on 2026-04-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0004_monitoringdiscovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='origin_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WafBypassFinding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('technique', models.CharField(max_length=200)),
                ('is_successful', models.BooleanField(default=False)),
                ('payload_evidence', models.TextField(blank=True, null=True)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waf_bypass_findings', to='startScan.subdomain')),
            ],
        ),
    ]
