# Generated by Django 3.2.4 on 2022-02-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0005_ipaddress_subscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='subscan',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='subscan_ids',
            field=models.ManyToManyField(related_name='subscan_ids', to='startScan.SubScan'),
        ),
    ]
