# Generated by Django 3.2.23 on 2026-04-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0005_auto_20260427_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='origin_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
