# Generated by Django 3.2.4 on 2022-03-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0006_auto_20220228_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='subscan_ids',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='ip_subscan_ids',
            field=models.ManyToManyField(related_name='ip_subscan_ids', to='startScan.SubScan'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='vuln_subscan_ids',
            field=models.ManyToManyField(related_name='vuln_subscan_ids', to='startScan.SubScan'),
        ),
    ]
