# Generated by Django 3.2.23 on 2026-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0006_alter_subdomain_origin_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='origin_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
