# Generated by Django 3.1.6 on 2021-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0010_auto_20210608_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(related_name='ip', to='startScan.Ip'),
        ),
    ]
