# Generated by Django 3.1.6 on 2021-06-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0012_auto_20210608_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='is_cdn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(related_name='ip', to='startScan.Ip'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='is_cdn',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
