# Generated by Django 3.2.4 on 2022-03-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0013_auto_20220310_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryfile',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
