# Generated by Django 3.1.6 on 2021-06-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0013_auto_20210608_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='port',
            name='scan_history',
        ),
        migrations.RemoveField(
            model_name='port',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='port',
            name='target_domain',
        ),
        migrations.AddField(
            model_name='ip',
            name='ports',
            field=models.ManyToManyField(related_name='port', to='startScan.Port'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(related_name='ip', to='startScan.Ip'),
        ),
    ]
