# Generated by Django 3.2.4 on 2022-03-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0014_directoryfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='directories',
            field=models.ManyToManyField(blank=True, related_name='directories', to='startScan.DirectoryScan'),
        ),
    ]
