# Generated by Django 3.2.4 on 2022-03-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0015_alter_subdomain_directories'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryscan',
            name='scanned_date',
            field=models.DateTimeField(null=True),
        ),
    ]
