# Generated by Django 3.1.6 on 2021-06-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0015_auto_20210609_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(related_name='ips', to='startScan.Ip'),
        ),
    ]
