# Generated by Django 3.2.4 on 2022-05-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0023_auto_20220430_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dork',
            name='url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='http_url',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='metafinderdocument',
            name='url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='cname',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='curl_command',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
    ]
