# Generated by Django 3.1.6 on 2021-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0024_remove_subdomain_ip_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(related_name='ips', to='startScan.Ip'),
        ),
    ]
