# Generated by Django 3.2.4 on 2022-05-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0025_auto_20220526_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='http_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='template_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilityreference',
            name='url',
            field=models.CharField(max_length=5000),
        ),
    ]
