# Generated by Django 3.2.4 on 2022-07-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0027_auto_20220709_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryiso',
            name='iso',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='countryiso',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
