# Generated by Django 3.1.6 on 2021-06-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0029_auto_20210609_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rrrrr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(related_name='ips', to='startScan.Rrrrr'),
        ),
    ]
