# Generated by Django 3.2.4 on 2022-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0030_auto_20220718_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscan',
            name='dir_file_fuzz',
        ),
        migrations.RemoveField(
            model_name='subscan',
            name='fetch_url',
        ),
        migrations.RemoveField(
            model_name='subscan',
            name='osint',
        ),
        migrations.RemoveField(
            model_name='subscan',
            name='port_scan',
        ),
        migrations.RemoveField(
            model_name='subscan',
            name='vulnerability_scan',
        ),
        migrations.AddField(
            model_name='subscan',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
