# Generated by Django 3.2.4 on 2022-09-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0031_auto_20220910_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistory',
            name='celery_id',
        ),
        migrations.RemoveField(
            model_name='subscan',
            name='celery_id',
        ),
    ]
