# Generated by Django 3.2.4 on 2022-08-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0031_auto_20220803_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='http_crawl',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
