# Generated by Django 3.2.4 on 2023-04-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0032_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='cdn_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
