# Generated by Django 3.2.4 on 2022-09-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0032_auto_20220816_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='scan_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory'),
        ),
    ]
