# Generated by Django 3.2.4 on 2022-09-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0032_auto_20220916_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscan',
            name='subdomain_subscan_ids',
            field=models.ManyToManyField(blank=True, related_name='subdomain_subscan_ids', to='startScan.Subdomain'),
        ),
    ]
