# Generated by Django 3.2.4 on 2022-09-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0033_alter_endpoint_scan_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='reverse_pointer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
