# Generated by Django 3.2.4 on 2022-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0034_auto_20220908_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanactivity',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
