# Generated by Django 3.2.4 on 2022-09-09 10:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0035_scanactivity_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='celery_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
