# Generated by Django 3.1.6 on 2021-06-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0035_auto_20210609_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='http_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
