# Generated by Django 3.2.4 on 2022-09-10 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0037_subscan_celery_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='celery_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='subscan',
            name='celery_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
