# Generated by Django 3.1.6 on 2021-06-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0037_auto_20210615_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='is_cdn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
