# Generated by Django 3.2.4 on 2022-09-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0038_auto_20220910_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanactivity',
            name='name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
