# Generated by Django 3.2.4 on 2023-07-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0038_auto_20230717_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='impact',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='remediation',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
