# Generated by Django 3.1.6 on 2021-06-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0040_auto_20210615_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='http_status',
            field=models.IntegerField(default=0),
        ),
    ]
