# Generated by Django 3.2.4 on 2021-06-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0045_auto_20210616_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
