# Generated by Django 3.2.4 on 2023-08-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0046_gptvulnerabilityreport_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='attack_surface',
            field=models.TextField(blank=True, null=True),
        ),
    ]
