# Generated by Django 3.2.4 on 2021-06-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0046_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='emails',
            field=models.ManyToManyField(related_name='emails', to='startScan.Email'),
        ),
    ]
