# Generated by Django 3.2.4 on 2023-09-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0047_subdomain_attack_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
