# Generated by Django 3.2.4 on 2021-06-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0049_scanhistory_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='designation',
        ),
    ]
