# Generated by Django 3.2.4 on 2021-06-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0051_auto_20210626_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('url', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
