# Generated by Django 3.2.4 on 2021-06-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0052_dork'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='dorks',
            field=models.ManyToManyField(related_name='dorks', to='startScan.Dork'),
        ),
    ]
