# Generated by Django 3.2.4 on 2021-06-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0053_scanhistory_dorks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='results_dir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='screenshot',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
