# Generated by Django 3.2.4 on 2021-07-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0054_auto_20210628_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metafinderdocument',
            old_name='name',
            new_name='doc_name',
        ),
    ]
