# Generated by Django 3.2.4 on 2021-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0055_rename_name_metafinderdocument_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
