# Generated by Django 3.2.4 on 2021-07-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0057_todonote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoNote',
        ),
    ]
