# Generated by Django 3.2.4 on 2021-07-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0058_delete_todonote'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
