# Generated by Django 3.2.4 on 2021-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0059_subdomain_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='is_important',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
