# Generated by Django 3.1.3 on 2021-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_name', models.CharField(max_length=200)),
                ('hook_url', models.CharField(max_length=500)),
                ('send_notif', models.BooleanField()),
            ],
        ),
    ]
