# Generated by Django 3.0.7 on 2020-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhooks',
            name='send_notif',
            field=models.BooleanField(default=True),
        ),
    ]
