# Generated by Django 3.0.7 on 2020-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200630_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhooks',
            name='send_notif',
            field=models.BooleanField(),
        ),
    ]
