# Generated by Django 3.2.23 on 2024-06-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetlasAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OllamaSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_model', models.CharField(max_length=500)),
                ('use_ollama', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAiAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('insert_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
            ],
        ),
    ]
