# Generated by Django 3.2.4 on 2022-04-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='name',
            new_name='query',
        ),
    ]
