# Generated by Django 3.2.23 on 2026-04-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensysAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.CharField(max_length=500)),
                ('api_secret', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShodanAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
