# Generated by Django 3.2.4 on 2023-06-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
