# Generated by Django 3.2.23 on 2026-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_censysapikey_shodanapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('selected_model', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
