# Generated by Django 3.2.23 on 2024-08-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_notification_inappnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'system'), ('project', 'project')], default='system', max_length=10),
        ),
    ]
