# Generated by Django 3.2.23 on 2024-08-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_inappnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('info', 'Informational'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10),
        ),
    ]
