# Generated by Django 3.2.4 on 2023-07-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_project_insert_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIKeys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
