# Generated by Django 3.2.23 on 2024-08-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_inappnotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='redirect_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
