# Generated by Django 3.2.4 on 2023-07-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_netlasapikey_openaiapikey'),
        ('dashboard', '0007_openaikeys'),
    ]

    operations = [
    ]
