# Generated by Django 3.2.23 on 2024-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20240831_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaosAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
