# Generated by Django 3.2.4 on 2024-04-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_ollamasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ollamasettings',
            name='is_ollama',
            field=models.BooleanField(default=False),
        ),
    ]
