# Generated by Django 3.2.4 on 2024-04-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20240421_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ollamasettings',
            old_name='is_ollama',
            new_name='use_ollama',
        ),
    ]
