from enum import Enum


class SubdomainSource(Enum):
    TARGET = "target"
    SUBFINDER = "subfinder"
    CTFR = "ctfr"
    CRTNAME = "crtname"
    SUBLIST3R = "sublist3r"
    ASSETFINDER = "assetfinder"
    AMASS = "amass"
    TLSX = "tlsx"
    ONEFORALL = "oneforall"
    NETLAS = "netlas"
    SUDOMY = "sudomy"
    SECURITYTRAILS = "securitytrails"
    CHAOS = "chaos"
    CENSYS = "censys"
    VIRUSTOTAL = "virustotal"
    BINARYEDGE = "binaryedge"
    BRUTEFORCE = "bruteforce"
    PERMUTATION = "permutation"
    ZONE_TRANSFER = "zone_transfer"
    SCRAPING = "scraping"
    TLS_CERT = "tls_cert"
    VHOST = "vhost"
    OTHER = "other"
