from enum import Enum


class SubdomainSource(Enum):
    TARGET = "target"
    SUBFINDER = "subfinder"
    CTFR = "ctfr"
    CRTNAME = "crtname"
    ASSETFINDER = "assetfinder"
    AMASS = "amass"
    TLSX = "tlsx"
    NETLAS = "netlas"
    BRUTEFORCE = "bruteforce"
    PERMUTATION = "permutation"
    ZONE_TRANSFER = "zone_transfer"
    GITHUB = "github"
    TLS_CERT = "tls_cert"
    PAGE_LINK = "page_link"
    RESPONSE_HEADER = "response_header"
    REDIRECT = "redirect"
    CT_LOG = "ct_log"
    IMPORTED = "imported"
    VHOST = "vhost"
    NETBLOCK = "netblock"
    HUDSON_ROCK = "hudson_rock"
