# Generated by Django 3.1.6 on 2021-04-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targetApp', '__first__'),
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scan_date', models.DateTimeField()),
                ('scan_status', models.IntegerField()),
                ('celery_id', models.CharField(blank=True, max_length=100)),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('scan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanEngine.enginetype')),
            ],
        ),
        migrations.CreateModel(
            name='ScannedHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=1000)),
                ('cname', models.CharField(blank=True, max_length=500)),
                ('open_ports', models.CharField(max_length=1000)),
                ('http_status', models.IntegerField(default=0)),
                ('content_length', models.IntegerField(default=0)),
                ('page_title', models.CharField(max_length=1000)),
                ('http_url', models.CharField(max_length=1000)),
                ('ip_address', models.CharField(max_length=1000)),
                ('is_ip_cdn', models.BooleanField(default=False, null=True)),
                ('screenshot_path', models.CharField(max_length=1000, null=True)),
                ('http_header_path', models.CharField(max_length=1000, null=True)),
                ('technology_stack', models.CharField(max_length=1500, null=True)),
                ('directory_json', models.JSONField(null=True)),
                ('checked', models.BooleanField(blank=True, default=False, null=True)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
        migrations.CreateModel(
            name='WayBackEndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_url', models.CharField(max_length=5000)),
                ('content_length', models.IntegerField(default=0)),
                ('page_title', models.CharField(max_length=1000)),
                ('http_status', models.IntegerField(default=0)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('url_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_date', models.DateTimeField(null=True)),
                ('url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=400)),
                ('severity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('extracted_results', models.CharField(blank=True, max_length=1000, null=True)),
                ('template_used', models.CharField(max_length=100)),
                ('matcher_name', models.CharField(blank=True, max_length=400, null=True)),
                ('open_status', models.BooleanField(blank=True, default=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scannedhost')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('vulnerability_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='ScanActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('scan_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
        ),
    ]
