# Generated by Django 3.0.6 on 2020-05-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanEngine', '0001_initial'),
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scan_date', models.DateTimeField()),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.Domain')),
                ('scan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanEngine.EngineType')),
            ],
        ),
    ]
