# Generated by Django 3.1.3 on 2021-03-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '__first__'),
        ('startScan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='target_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain'),
        ),
    ]
