# Generated by Django 3.0.6 on 2020-05-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistorymodel',
            name='scan_status',
            field=models.CharField(default='Scanning', max_length=100),
        ),
    ]
