# Generated by Django 3.0.7 on 2020-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='celery_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
