# Generated by Django 3.1.6 on 2021-04-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='whois_json',
            field=models.JSONField(null=True),
        ),
    ]
