# Generated by Django 3.1.6 on 2021-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_scanhistory_whois_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanhistory',
            old_name='last_scan_date',
            new_name='scan_start_date',
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='scan_stop_date',
            field=models.DateTimeField(null=True),
        ),
    ]
