# Generated by Django 3.0.6 on 2020-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_scanhistorymodel_scan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistorymodel',
            name='scan_status',
            field=models.IntegerField(),
        ),
    ]
