# Generated by Django 3.1.3 on 2021-03-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_scannedhost_target_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scannedhost',
            old_name='target_host',
            new_name='target_domain',
        ),
    ]
