# Generated by Django 3.0.7 on 2020-07-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_scanvulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanvulnerability',
            name='matcher',
            field=models.CharField(default='--', max_length=1000),
        ),
    ]
