# Generated by Django 3.0.7 on 2020-10-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_scanhistory_celery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybackendpoint',
            name='content_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
