# Generated by Django 3.0.6 on 2020-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0002_auto_20200516_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
