# Generated by Django 3.0.6 on 2020-05-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_backgroundscan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundScan',
        ),
    ]
