# Generated by Django 3.1.6 on 2021-05-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_auto_20210502_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanhistory',
            old_name='scan_start_date',
            new_name='start_scan_date',
        ),
        migrations.RenameField(
            model_name='scanhistory',
            old_name='scan_stop_date',
            new_name='stop_scan_date',
        ),
    ]
