# Generated by Django 3.0.7 on 2020-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_waybackendpoint_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='is_ip_cdn',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
