# Generated by Django 3.1.3 on 2021-03-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '__first__'),
        ('startScan', '0003_auto_20210303_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilityscan',
            name='target_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain'),
        ),
        migrations.AddField(
            model_name='waybackendpoint',
            name='target_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain'),
        ),
    ]
