# Generated by Django 3.0.6 on 2020-05-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0003_auto_20200513_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedSubdomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=100)),
                ('open_ports', models.CharField(max_length=1000)),
                ('takeover_possible', models.BooleanField()),
                ('technology_stack', models.CharField(max_length=1000)),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.ScanHistoryModel')),
            ],
        ),
    ]
