# Generated by Django 3.0.7 on 2020-07-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0004_auto_20200728_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanvulnerability',
            old_name='scan_history',
            new_name='scan_id',
        ),
    ]
