# Generated by Django 3.1.3 on 2021-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0004_auto_20210303_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='interesting_subdomain',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scannedhost',
            name='interesting_subdomain_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
