# Generated by Django 3.0.7 on 2020-10-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0004_scannedhost_is_ip_cdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='cname',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
