# Generated by Django 3.0.6 on 2020-05-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0004_delete_backgroundscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedsubdomains',
            name='subdomain',
            field=models.CharField(max_length=1000),
        ),
    ]
