# Generated by Django 3.0.6 on 2020-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0004_scannedsubdomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedsubdomains',
            name='alive_subdomain',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
