# Generated by Django 3.0.7 on 2020-07-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0005_auto_20200728_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanactivity',
            old_name='scan_id',
            new_name='scan_of',
        ),
    ]
