# Generated by Django 3.1.3 on 2021-03-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0005_auto_20210303_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedhost',
            name='interesting_subdomain',
        ),
        migrations.RemoveField(
            model_name='scannedhost',
            name='interesting_subdomain_reason',
        ),
    ]
