# Generated by Django 3.1.6 on 2021-05-05 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_auto_20210502_0601'),
        ('startScan', '0005_auto_20210504_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_url', models.CharField(max_length=5000)),
                ('content_length', models.IntegerField(default=0)),
                ('page_title', models.CharField(max_length=1000)),
                ('http_status', models.IntegerField(default=0)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('sub_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scannedhost')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('url_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
        ),
        migrations.AlterField(
            model_name='vulnerabilityscan',
            name='matched_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.endpoint'),
        ),
        migrations.DeleteModel(
            name='WayBackEndPoint',
        ),
    ]
