# Generated by Django 3.0.6 on 2020-05-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0005_auto_20200524_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=1000)),
                ('open_ports', models.CharField(max_length=1000)),
                ('takeover_possible', models.BooleanField()),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.ScanHistory')),
            ],
        ),
        migrations.CreateModel(
            name='ScannedSubdomainWithProtocols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('ip_address', models.CharField(max_length=1000)),
                ('page_title', models.CharField(max_length=1000)),
                ('http_status', models.IntegerField()),
                ('technology_stack', models.CharField(max_length=1000)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.ScannedHost')),
            ],
        ),
        migrations.DeleteModel(
            name='ScannedSubdomains',
        ),
    ]
