# Generated by Django 3.0.7 on 2020-10-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0006_vulnerabilityscanner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VulnerabilityScanner',
            new_name='VulnerabilityScan',
        ),
    ]
