# Generated by Django 3.0.6 on 2020-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0006_auto_20200524_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedsubdomainwithprotocols',
            name='screenshot_path',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
