# Generated by Django 3.0.7 on 2020-08-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0006_auto_20200728_1957'),
        ('startScan', '0003_auto_20200731_1016'),
    ]

    operations = [
    ]
