# Generated by Django 3.1.6 on 2021-05-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0006_auto_20210505_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='url_of',
            new_name='scan_history',
        ),
        migrations.RenameField(
            model_name='endpoint',
            old_name='sub_domain',
            new_name='scanned_host',
        ),
        migrations.RenameField(
            model_name='vulnerabilityscan',
            old_name='target_domain',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='vulnerabilityscan',
            old_name='matched_url',
            new_name='endpoint',
        ),
        migrations.RenameField(
            model_name='vulnerabilityscan',
            old_name='vulnerability_of',
            new_name='scan_history',
        ),
    ]
