# Generated by Django 3.1.6 on 2021-05-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_auto_20210502_0601'),
        ('startScan', '0007_auto_20210505_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('cname', models.CharField(blank=True, max_length=500)),
                ('open_ports', models.CharField(max_length=1000)),
                ('http_status', models.IntegerField(default=0)),
                ('content_length', models.IntegerField(default=0)),
                ('page_title', models.CharField(max_length=1000)),
                ('http_url', models.CharField(max_length=1000)),
                ('ip_address', models.CharField(max_length=1000)),
                ('is_ip_cdn', models.BooleanField(default=False, null=True)),
                ('screenshot_path', models.CharField(max_length=1000, null=True)),
                ('http_header_path', models.CharField(max_length=1000, null=True)),
                ('technology_stack', models.CharField(max_length=1500, null=True)),
                ('directory_json', models.JSONField(null=True)),
                ('checked', models.BooleanField(blank=True, default=False, null=True)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='scanned_host',
        ),
        migrations.DeleteModel(
            name='ScannedHost',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain'),
        ),
    ]
