# Generated by Django 3.0.6 on 2020-05-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0007_scannedsubdomainwithprotocols_screenshot_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedsubdomainwithprotocols',
            name='http_header_path',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
