# Generated by Django 3.0.7 on 2020-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0008_auto_20201010_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilityscan',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilityscan',
            name='extracted_results',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilityscan',
            name='matcher_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
