# Generated by Django 3.0.6 on 2020-05-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0009_auto_20200531_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='http_url',
            field=models.CharField(default='#', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scannedhost',
            name='content_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scannedhost',
            name='http_status',
            field=models.IntegerField(default=0),
        ),
    ]
