# Generated by Django 3.1.6 on 2021-05-06 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0011_auto_20210505_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerability',
            old_name='domain',
            new_name='target_domain',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain'),
        ),
    ]
