# Generated by Django 3.0.6 on 2020-05-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0011_auto_20200531_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='technology_stack',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
