# Generated by Django 3.0.7 on 2020-11-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0011_vulnerabilityscan_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedhost',
            name='takeover',
        ),
    ]
