# Generated by Django 3.0.6 on 2020-05-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0012_scannedhost_technology_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=1000),
            preserve_default=False,
        ),
    ]
