# Generated by Django 3.1.6 on 2021-05-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0013_auto_20210506_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='reference',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
