# Generated by Django 3.0.6 on 2020-05-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0013_scannedhost_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=1000)),
                ('activity_time', models.DateTimeField()),
                ('activity_status', models.CharField(max_length=100)),
                ('scan_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.ScanHistory')),
            ],
        ),
    ]
