# Generated by Django 3.0.6 on 2020-05-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0014_scanstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('scan_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.ScanHistory')),
            ],
        ),
        migrations.DeleteModel(
            name='ScanStatus',
        ),
    ]
