# Generated by Django 3.1.6 on 2021-05-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0014_auto_20210507_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='is_external',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='technology_stack',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='webserver',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
