# Generated by Django 3.0.7 on 2020-11-26 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0015_scannedhost_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='date_discovered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
