# Generated by Django 3.1.6 on 2021-05-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0015_auto_20210509_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='extracted_results',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
