# Generated by Django 3.1.6 on 2021-05-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0016_auto_20210510_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='is_external',
            new_name='is_default',
        ),
    ]
