# Generated by Django 3.0.6 on 2020-05-31 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0016_auto_20200531_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='WayBackEndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_url', models.CharField(max_length=1000)),
                ('content_length', models.IntegerField(default=0)),
                ('page_title', models.CharField(max_length=1000)),
                ('http_status', models.IntegerField(default=0)),
                ('url_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.ScanHistory')),
            ],
        ),
    ]
