# Generated by Django 3.1.6 on 2021-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0017_auto_20210511_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='ip_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
