# Generated by Django 3.0.7 on 2020-11-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0017_auto_20201126_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedhost',
            name='discovered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
