# Generated by Django 3.1.6 on 2021-05-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0018_auto_20210511_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='content_length',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='http_status',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='is_ip_cdn',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='technology_stack',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='cname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_cdn',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
