# Generated by Django 3.0.7 on 2020-07-02 16:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0018_scannedhost_directory_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedhost',
            name='directory_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='', null=True),
        ),
    ]
