# Generated by Django 3.1.3 on 2020-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0018_auto_20201126_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedhost',
            name='directory_json',
            field=models.JSONField(null=True),
        ),
    ]
