# Generated by Django 3.1.6 on 2021-05-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0019_auto_20210511_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='cname',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='http_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='ip_address',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='is_cdn',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='technology_stack',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='webserver',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='cname',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='ip_address',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='technology_stack',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
