# Generated by Django 3.1.6 on 2021-05-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0020_auto_20210512_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='content_length',
            field=models.IntegerField(default=0),
        ),
    ]
