# Generated by Django 3.0.7 on 2020-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0020_auto_20200702_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanactivity',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
