# Generated by Django 3.1.3 on 2020-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0020_waybackendpoint_discovered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilityscan',
            name='severity',
            field=models.CharField(max_length=100),
        ),
    ]
