# Generated by Django 3.1.3 on 2020-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0021_auto_20201128_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilityscan',
            name='severity',
            field=models.IntegerField(),
        ),
    ]
