# Generated by Django 3.1.6 on 2021-05-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0021_subdomain_content_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='page_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
