# Generated by Django 3.0.7 on 2020-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0021_auto_20200702_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhost',
            name='takeover',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
