# Generated by Django 3.1.6 on 2021-05-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0022_subdomain_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='host_ip',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='host_ip',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
