# Generated by Django 3.1.6 on 2021-06-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0022_auto_20210609_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='ports',
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ip_addresses',
            field=models.ManyToManyField(related_name='ips', to='startScan.Technology'),
        ),
    ]
