# Generated by Django 3.0.7 on 2020-07-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0022_scannedhost_takeover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybackendpoint',
            name='http_url',
            field=models.CharField(max_length=5000),
        ),
    ]
