# Generated by Django 3.1.6 on 2021-06-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0023_auto_20210609_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='ip_addresses',
        ),
    ]
