# Generated by Django 3.1.6 on 2021-05-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0023_auto_20210513_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='ip_address',
            new_name='ip_addresses',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='ip_address',
            new_name='ip_addresses',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='is_cdn',
        ),
    ]
