# Generated by Django 3.1.6 on 2021-05-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0024_auto_20210513_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='directory_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='http_header_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='open_ports',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
