# Generated by Django 3.1.6 on 2021-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0025_auto_20210513_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistory',
            name='whois_json',
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='dir_file_search',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='fetch_url',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='port_scan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='subdomain_discovery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='vulnerability_scan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
