# Generated by Django 3.1.6 on 2021-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0027_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='is_uncommon',
            field=models.BooleanField(default=False),
        ),
    ]
