# Generated by Django 3.1.6 on 2021-05-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0029_auto_20210514_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='ip',
            new_name='address',
        ),
    ]
