# Generated by Django 3.1.6 on 2021-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0030_auto_20210514_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
