# Generated by Django 3.1.6 on 2021-05-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0031_ipaddress_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='is_cdn',
            field=models.BooleanField(default=False),
        ),
    ]
