# Generated by Django 3.1.6 on 2021-05-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0032_ipaddress_is_cdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='is_lfi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_rce',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_redirect',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_sqli',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_ssrf',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_ssti',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_xss',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='matched_gf',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
