# Generated by Django 3.1.6 on 2021-05-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0034_auto_20210515_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='matched_patterns',
            new_name='matched_gf_patterns',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='is_lfi',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='is_rce',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='is_redirect',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='is_sqli',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='is_ssrf',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='is_ssti',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='is_xss',
        ),
    ]
