# Generated by Django 3.1.6 on 2021-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0035_auto_20210517_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='used_gf_patterns',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
