# Generated by Django 3.1.6 on 2021-05-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0036_endpoint_used_gf_patterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='used_gf_patterns',
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='used_gf_patterns',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
