# Generated by Django 3.1.6 on 2021-05-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0037_auto_20210517_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='open_ports',
        ),
    ]
