# Generated by Django 3.1.6 on 2021-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0038_remove_subdomain_open_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='is_imported_subdomain',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
