# Generated by Django 3.1.6 on 2021-06-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0038_auto_20210615_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='content_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
