# Generated by Django 3.1.6 on 2021-06-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0039_subdomain_is_imported_subdomain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanhistory',
            old_name='domain_name',
            new_name='domain',
        ),
    ]
