# Generated by Django 3.1.6 on 2021-06-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0004_auto_20210607_0439'),
        ('startScan', '0040_auto_20210606_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='host_ip',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='ip_addresses',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='technology_stack',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='technology_stack',
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.endpoint')),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
    ]
