# Generated by Django 3.1.6 on 2021-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0041_auto_20210615_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='content_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='http_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='page_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
