# Generated by Django 3.1.6 on 2021-06-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0041_auto_20210608_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='scan_history',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='target_domain',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='technologies',
            field=models.ManyToManyField(to='startScan.Technology'),
        ),
    ]
