# Generated by Django 3.1.6 on 2021-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0042_auto_20210608_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='technologies',
            field=models.ManyToManyField(to='startScan.Technology'),
        ),
    ]
