# Generated by Django 3.2.4 on 2023-06-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_project_slug'),
        ('recon_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonote',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
            preserve_default=False,
        ),
    ]
