# Generated by Django 3.2.23 on 2024-05-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startScan', '0001_initial'),
        ('recon_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonote',
            name='scan_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory'),
        ),
        migrations.AddField(
            model_name='todonote',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain'),
        ),
    ]
