name: 🐞 Bug
description: File a bug/issue
title: "bug: <title>"
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **reNgine**: 3.0.0
        - **Install**: install.sh / install.sh --build / dev compose
        - **OS**: Ubuntu 24.04
        - **Docker Engine**: 27.3.1
        - **Docker Compose**: 2.29.7
        - **Browser**: Firefox 131
    value: |
        - reNgine:
        - Install:
        - OS:
        - Docker Engine:
        - Docker Compose:
        - Browser:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Logs, screenshots or links related to the issue.

      Images and log files can be attached by dragging them into this field.
  validations:
    required: false
