name: reNgine-ng documentation
description: You want to improve the documentation of reNgine-ng which is either a Markdown file or the Wiki
title: "docs(scope): "
labels: ["documentation"]
body:
- type: textarea
  id: documentation-description
  attributes:
    label: Describe the documentation you want to change
    description: A clear description of what you want to change.
  validations:
    required: true

- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgements
    description: Your feature request will be closed if you don't follow the checklist below.
    options:
      - label: This issue is not a duplicate of an existing documentation change request.
        required: true
      - label: I have chosen an appropriate title.
        required: true
      - label: All requested information has been provided properly.
        required: true
