"""add viewdns

Revision ID: 6ea7f707215f
Revises: 25dbefe3271f
Create Date: 2026-02-09 08:34:40.436577+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ea7f707215f'
down_revision: Union[str, None] = '25dbefe3271f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewdns_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lookup_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_type', 'query_value', name='uq_viewdns_cache_lookup')
    )
    op.create_index(op.f('ix_viewdns_cache_id'), 'viewdns_cache', ['id'], unique=False)
    op.create_index(op.f('ix_viewdns_cache_lookup_type'), 'viewdns_cache', ['lookup_type'], unique=False)
    op.create_index(op.f('ix_viewdns_cache_query_value'), 'viewdns_cache', ['query_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viewdns_cache_query_value'), table_name='viewdns_cache')
    op.drop_index(op.f('ix_viewdns_cache_lookup_type'), table_name='viewdns_cache')
    op.drop_index(op.f('ix_viewdns_cache_id'), table_name='viewdns_cache')
    op.drop_table('viewdns_cache')
    # ### end Alembic commands ###
