"""add dnsx, cleanup old

Revision ID: e1be90b7d53b
Revises:
Create Date: 2026-02-10 16:33:55.515015+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1be90b7d53b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('VIEWDNS', name='apiprovider'), nullable=False),
    sa.Column('key_value', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('usage_counter', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', name='uq_api_key_provider')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_provider'), 'api_keys', ['provider'], unique=False)
    op.create_table('dns_lookups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cdn', sa.Boolean(), nullable=False),
    sa.Column('cdn_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_lookups_id'), 'dns_lookups', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('type', sa.Enum('SCAN', 'SYSTEM', 'SECURITY', 'VULNERABILITY', 'TARGET', 'RESOURCE', 'INTEGRATION', name='notificationtype'), nullable=False),
    sa.Column('severity', sa.Enum('SUCCESS', 'INFO', 'WARNING', 'ERROR', name='notificationseverity'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_expires_at'), 'notifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_table('ripestat_abuse_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abuse_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ripestat_ac_resource', 'ripestat_abuse_contacts', ['resource'], unique=False)
    op.create_table('ripestat_announced_prefixes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_version', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ripestat_ap_asn', 'ripestat_announced_prefixes', ['asn'], unique=False)
    op.create_index('ix_ripestat_ap_prefix', 'ripestat_announced_prefixes', ['prefix'], unique=False)
    op.create_table('ripestat_as_overviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('announced', sa.Boolean(), nullable=False),
    sa.Column('block_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('block_resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asn', name='uq_ripestat_as_overview_asn')
    )
    op.create_index(op.f('ix_ripestat_as_overviews_asn'), 'ripestat_as_overviews', ['asn'], unique=False)
    op.create_index('ix_ripestat_aso_holder', 'ripestat_as_overviews', ['holder'], unique=False)
    op.create_table('ripestat_asn_neighbours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('neighbour_asn', sa.Integer(), nullable=False),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ripestat_an_asn', 'ripestat_asn_neighbours', ['asn'], unique=False)
    op.create_index('ix_ripestat_an_neighbour', 'ripestat_asn_neighbours', ['neighbour_asn'], unique=False)
    op.create_table('ripestat_network_info',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ripestat_ni_asn', 'ripestat_network_info', ['asn'], unique=False)
    op.create_index('ix_ripestat_ni_ip', 'ripestat_network_info', ['ip'], unique=False)
    op.create_index('ix_ripestat_ni_prefix', 'ripestat_network_info', ['prefix'], unique=False)
    op.create_table('ripestat_prefix_overviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_announced', sa.Boolean(), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ripestat_po_asn', 'ripestat_prefix_overviews', ['asn'], unique=False)
    op.create_index('ix_ripestat_po_prefix', 'ripestat_prefix_overviews', ['prefix'], unique=False)
    op.create_table('ripestat_query_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lookup_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_type', 'query_value', name='uq_ripestat_query_log_lookup')
    )
    op.create_index(op.f('ix_ripestat_query_log_lookup_type'), 'ripestat_query_log', ['lookup_type'], unique=False)
    op.create_index(op.f('ix_ripestat_query_log_query_value'), 'ripestat_query_log', ['query_value'], unique=False)
    op.create_table('ripestat_related_prefixes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_asn', sa.Integer(), nullable=True),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ripestat_rp_prefix', 'ripestat_related_prefixes', ['prefix'], unique=False)
    op.create_index('ix_ripestat_rp_related', 'ripestat_related_prefixes', ['related_prefix'], unique=False)
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('viewdns_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lookup_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_type', 'query_value', name='uq_viewdns_cache_lookup')
    )
    op.create_index(op.f('ix_viewdns_cache_id'), 'viewdns_cache', ['id'], unique=False)
    op.create_index(op.f('ix_viewdns_cache_lookup_type'), 'viewdns_cache', ['lookup_type'], unique=False)
    op.create_index(op.f('ix_viewdns_cache_query_value'), 'viewdns_cache', ['query_value'], unique=False)
    op.create_table('whois_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_value', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('lookup_type', sa.Enum('DOMAIN', 'IP', 'ASN', name='whoislookuptype'), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('whois_server', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('object_class', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rir', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_changed_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('registrant_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('registrant_email', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('registrar_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('abuse_email', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('nameservers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domain_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dnssec', sa.Boolean(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('ip_version', sa.Integer(), nullable=True),
    sa.Column('assignment_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('network_cidr', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('asn_range_start', sa.Integer(), nullable=True),
    sa.Column('asn_range_end', sa.Integer(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whois_records_country'), 'whois_records', ['country'], unique=False)
    op.create_index(op.f('ix_whois_records_id'), 'whois_records', ['id'], unique=False)
    op.create_index(op.f('ix_whois_records_name'), 'whois_records', ['name'], unique=False)
    op.create_index(op.f('ix_whois_records_network_cidr'), 'whois_records', ['network_cidr'], unique=False)
    op.create_index(op.f('ix_whois_records_query_value'), 'whois_records', ['query_value'], unique=True)
    op.create_index(op.f('ix_whois_records_registrant_email'), 'whois_records', ['registrant_email'], unique=False)
    op.create_index(op.f('ix_whois_records_registrant_name'), 'whois_records', ['registrant_name'], unique=False)
    op.create_index(op.f('ix_whois_records_registrar_name'), 'whois_records', ['registrar_name'], unique=False)
    op.create_table('projects',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('whois_nameservers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('whois_record_id', sa.Uuid(), nullable=False),
    sa.Column('nameserver', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.ForeignKeyConstraint(['whois_record_id'], ['whois_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whois_nameservers_nameserver'), 'whois_nameservers', ['nameserver'], unique=False)
    op.create_index(op.f('ix_whois_nameservers_whois_record_id'), 'whois_nameservers', ['whois_record_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'project_id', name='uq_organization_name_project'),
    sa.UniqueConstraint('slug', 'project_id', name='uq_organization_slug_project')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_project_id'), 'organizations', ['project_id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.create_table('tags',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'project_id', name='uq_tag_name_project'),
    sa.UniqueConstraint('slug', 'project_id', name='uq_tag_slug_project')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_project_id'), 'tags', ['project_id'], unique=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=False)
    op.create_table('targets',
    sa.Column('target_value', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('DOMAIN', 'IP', 'IP_RANGE', 'ASN', 'URL', name='targettype'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('whois_status', sa.Enum('PENDING', 'QUERYING', 'SUCCESS', 'FAILED', 'SKIPPED', 'NOT_APPLICABLE', name='taskstatus'), nullable=False),
    sa.Column('whois_error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('whois_record_id', sa.Uuid(), nullable=True),
    sa.Column('bgp_status', sa.Enum('PENDING', 'QUERYING', 'SUCCESS', 'FAILED', 'SKIPPED', 'NOT_APPLICABLE', name='taskstatus'), nullable=False),
    sa.Column('dns_status', sa.Enum('PENDING', 'QUERYING', 'SUCCESS', 'FAILED', 'SKIPPED', 'NOT_APPLICABLE', name='taskstatus'), nullable=False),
    sa.Column('dns_error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('dns_lookup_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dns_lookup_id'], ['dns_lookups.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['whois_record_id'], ['whois_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_targets_bgp_status'), 'targets', ['bgp_status'], unique=False)
    op.create_index(op.f('ix_targets_dns_lookup_id'), 'targets', ['dns_lookup_id'], unique=False)
    op.create_index(op.f('ix_targets_dns_status'), 'targets', ['dns_status'], unique=False)
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_index(op.f('ix_targets_project_id'), 'targets', ['project_id'], unique=False)
    op.create_index(op.f('ix_targets_whois_record_id'), 'targets', ['whois_record_id'], unique=False)
    op.create_index(op.f('ix_targets_whois_status'), 'targets', ['whois_status'], unique=False)
    op.create_table('dns_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dns_lookup_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.Enum('A', 'AAAA', 'CNAME', 'NS', 'MX', 'TXT', 'SOA', 'SRV', 'PTR', 'CAA', 'AXFR', 'CDN', name='dnsrecordtype'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('soa_email', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('soa_serial', sa.Integer(), nullable=True),
    sa.Column('soa_refresh', sa.Integer(), nullable=True),
    sa.Column('soa_retry', sa.Integer(), nullable=True),
    sa.Column('soa_expire', sa.Integer(), nullable=True),
    sa.Column('soa_minttl', sa.Integer(), nullable=True),
    sa.Column('caa_tag', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('caa_flag', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dns_lookup_id'], ['dns_lookups.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_records_dns_lookup_id'), 'dns_records', ['dns_lookup_id'], unique=False)
    op.create_index(op.f('ix_dns_records_id'), 'dns_records', ['id'], unique=False)
    op.create_index(op.f('ix_dns_records_record_type'), 'dns_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_dns_records_target_id'), 'dns_records', ['target_id'], unique=False)
    op.create_index(op.f('ix_dns_records_value'), 'dns_records', ['value'], unique=False)
    op.create_table('target_bgp_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('prefix_count', sa.Integer(), nullable=True),
    sa.Column('peer_count', sa.Integer(), nullable=True),
    sa.Column('announced', sa.Boolean(), nullable=True),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_bgp_summaries_target_id'), 'target_bgp_summaries', ['target_id'], unique=True)
    op.create_table('target_organizations',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('target_id', 'organization_id')
    )
    op.create_table('target_tags',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('target_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_tags')
    op.drop_table('target_organizations')
    op.drop_index(op.f('ix_target_bgp_summaries_target_id'), table_name='target_bgp_summaries')
    op.drop_table('target_bgp_summaries')
    op.drop_index(op.f('ix_dns_records_value'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_target_id'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_record_type'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_id'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_dns_lookup_id'), table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_targets_whois_status'), table_name='targets')
    op.drop_index(op.f('ix_targets_whois_record_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_project_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_dns_status'), table_name='targets')
    op.drop_index(op.f('ix_targets_dns_lookup_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_bgp_status'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_project_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_project_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_whois_nameservers_whois_record_id'), table_name='whois_nameservers')
    op.drop_index(op.f('ix_whois_nameservers_nameserver'), table_name='whois_nameservers')
    op.drop_table('whois_nameservers')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_whois_records_registrar_name'), table_name='whois_records')
    op.drop_index(op.f('ix_whois_records_registrant_name'), table_name='whois_records')
    op.drop_index(op.f('ix_whois_records_registrant_email'), table_name='whois_records')
    op.drop_index(op.f('ix_whois_records_query_value'), table_name='whois_records')
    op.drop_index(op.f('ix_whois_records_network_cidr'), table_name='whois_records')
    op.drop_index(op.f('ix_whois_records_name'), table_name='whois_records')
    op.drop_index(op.f('ix_whois_records_id'), table_name='whois_records')
    op.drop_index(op.f('ix_whois_records_country'), table_name='whois_records')
    op.drop_table('whois_records')
    op.drop_index(op.f('ix_viewdns_cache_query_value'), table_name='viewdns_cache')
    op.drop_index(op.f('ix_viewdns_cache_lookup_type'), table_name='viewdns_cache')
    op.drop_index(op.f('ix_viewdns_cache_id'), table_name='viewdns_cache')
    op.drop_table('viewdns_cache')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ripestat_rp_related', table_name='ripestat_related_prefixes')
    op.drop_index('ix_ripestat_rp_prefix', table_name='ripestat_related_prefixes')
    op.drop_table('ripestat_related_prefixes')
    op.drop_index(op.f('ix_ripestat_query_log_query_value'), table_name='ripestat_query_log')
    op.drop_index(op.f('ix_ripestat_query_log_lookup_type'), table_name='ripestat_query_log')
    op.drop_table('ripestat_query_log')
    op.drop_index('ix_ripestat_po_prefix', table_name='ripestat_prefix_overviews')
    op.drop_index('ix_ripestat_po_asn', table_name='ripestat_prefix_overviews')
    op.drop_table('ripestat_prefix_overviews')
    op.drop_index('ix_ripestat_ni_prefix', table_name='ripestat_network_info')
    op.drop_index('ix_ripestat_ni_ip', table_name='ripestat_network_info')
    op.drop_index('ix_ripestat_ni_asn', table_name='ripestat_network_info')
    op.drop_table('ripestat_network_info')
    op.drop_index('ix_ripestat_an_neighbour', table_name='ripestat_asn_neighbours')
    op.drop_index('ix_ripestat_an_asn', table_name='ripestat_asn_neighbours')
    op.drop_table('ripestat_asn_neighbours')
    op.drop_index('ix_ripestat_aso_holder', table_name='ripestat_as_overviews')
    op.drop_index(op.f('ix_ripestat_as_overviews_asn'), table_name='ripestat_as_overviews')
    op.drop_table('ripestat_as_overviews')
    op.drop_index('ix_ripestat_ap_prefix', table_name='ripestat_announced_prefixes')
    op.drop_index('ix_ripestat_ap_asn', table_name='ripestat_announced_prefixes')
    op.drop_table('ripestat_announced_prefixes')
    op.drop_index('ix_ripestat_ac_resource', table_name='ripestat_abuse_contacts')
    op.drop_table('ripestat_abuse_contacts')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_expires_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_dns_lookups_id'), table_name='dns_lookups')
    op.drop_table('dns_lookups')
    op.drop_index(op.f('ix_api_keys_provider'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
