"""add activity log

Revision ID: d55cda538e83
Revises: c359e17eba19
Create Date: 2026-02-21 12:49:56.556592+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd55cda538e83'
down_revision: Union[str, None] = 'c359e17eba19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='activitylevel'), nullable=False),
    sa.Column('event_type', sa.Enum('TARGET_CREATED', 'TARGET_UPDATED', 'TARGET_DELETED', 'TARGET_BULK_IMPORTED', 'TARGET_ENRICHMENT_STARTED', 'TARGET_ENRICHMENT_WHOIS_COMPLETED', 'TARGET_ENRICHMENT_WHOIS_FAILED', 'TARGET_ENRICHMENT_DNS_COMPLETED', 'TARGET_ENRICHMENT_DNS_FAILED', 'TARGET_ENRICHMENT_BGP_COMPLETED', 'TARGET_ENRICHMENT_BGP_FAILED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'SYSTEM_USER_LOGIN', 'SYSTEM_USER_LOGOUT', 'SYSTEM_USER_CREATED', 'SYSTEM_CONFIG_UPDATED', name='activityevent'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_event_type'), 'activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_project_id'), 'activity_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_target_id'), 'activity_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_target_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_project_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_event_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
