# Generated by Django 3.1.6 on 2021-04-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=200)),
                ('subdomain_discovery', models.BooleanField()),
                ('dir_file_search', models.BooleanField()),
                ('port_scan', models.BooleanField()),
                ('fetch_url', models.BooleanField()),
                ('vulnerability_scan', models.BooleanField(default=False, null=True)),
                ('yaml_configuration', models.TextField()),
                ('default_engine', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestingLookupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('custom_type', models.BooleanField(default=False)),
                ('title_lookup', models.BooleanField(default=True)),
                ('url_lookup', models.BooleanField(default=True)),
                ('condition_200_http_lookup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
