# Generated by Django 3.0.6 on 2020-05-11 09:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type_name', models.CharField(max_length=200)),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[('subdomain_discovery', 'Subdomain Discovery'), ('visual_identification', 'Visual Idenfitication'), ('dir_file_search', 'Directory & Files Discovery'), ('subdomain_takeover', 'Subdomain Takeover'), ('param_discovery', 'Parameter Discovery'), ('port_scan', 'Port Scan')], max_length=102)),
            ],
        ),
    ]
