# Generated by Django 3.0.6 on 2020-05-11 16:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('subdomain_discovery', 'Subdomain Discovery'), ('dir_file_search', 'Directory & Files Discovery'), ('subdomain_takeover', 'Subdomain Takeover'), ('param_discovery', 'Parameter Discovery'), ('port_scan', 'Port Scan')], max_length=80),
        ),
    ]
