# Generated by Django 3.0.6 on 2020-05-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='dir_file_search',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='param_discovery',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='port_scan',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='subdomain_takeover',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
