# Generated by Django 3.0.7 on 2020-07-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginetype',
            name='param_discovery',
        ),
    ]
