# Generated by Django 3.0.7 on 2020-07-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enginetype',
            old_name='scan_type_name',
            new_name='engine_name',
        ),
    ]
