# Generated by Django 3.1.3 on 2021-03-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginetype',
            name='interesting_subdomain_lookup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
