# Generated by Django 3.0.6 on 2020-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0002_auto_20200513_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='dir_file_search',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='param_discovery',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='port_scan',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='subdomain_discovery',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='subdomain_takeover',
            field=models.BooleanField(),
        ),
    ]
