# Generated by Django 3.0.6 on 2020-05-11 17:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0002_auto_20200511_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginetype',
            name='my_field',
        ),
        migrations.AddField(
            model_name='enginetype',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('subdomain_discovery', 'Subdomain Discovery'), ('dir_file_search', 'Directory & Files Discovery'), ('subdomain_takeover', 'Subdomain Takeover'), ('param_discovery', 'Parameter Discovery'), ('port_scan', 'Port Scan')], default=None, max_length=80),
        ),
    ]
