# Generated by Django 3.0.7 on 2020-07-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_enginetype_fetch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginetype',
            name='default_engine',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
