# Generated by Django 3.0.7 on 2020-07-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_wordlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='short_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
