# Generated by Django 3.1.3 on 2021-03-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_auto_20210307_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestinglookupmodel',
            name='custom_type',
            field=models.BooleanField(default=False),
        ),
    ]
