# Generated by Django 3.0.6 on 2020-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_auto_20200513_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='port_scan',
            field=models.BooleanField(default=True),
        ),
    ]
