# Generated by Django 3.0.6 on 2020-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_auto_20200511_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginetype',
            name='fields',
        ),
        migrations.AddField(
            model_name='enginetype',
            name='dir_file_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enginetype',
            name='param_discovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enginetype',
            name='port_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enginetype',
            name='subdomain_discovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enginetype',
            name='subdomain_takeover',
            field=models.BooleanField(default=False),
        ),
    ]
