# Generated by Django 3.1.3 on 2021-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0004_interestinglookupmodel_custom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestinglookupmodel',
            name='title_lookup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interestinglookupmodel',
            name='url_lookup',
            field=models.BooleanField(default=True),
        ),
    ]
