# Generated by Django 3.0.7 on 2020-07-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0004_enginetype_default_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='default_engine',
            field=models.BooleanField(default=False),
        ),
    ]
