# Generated by Django 3.0.7 on 2020-07-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0005_auto_20200718_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
