# Generated by Django 3.0.7 on 2020-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0005_auto_20200707_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='default_engine',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
