# Generated by Django 3.1.3 on 2021-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0005_auto_20210313_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestinglookupmodel',
            name='condition_200_http_lookup',
            field=models.BooleanField(default=False),
        ),
    ]
