# Generated by Django 3.0.7 on 2020-07-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0006_auto_20200718_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='path',
        ),
    ]
