# Generated by Django 3.0.7 on 2020-07-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0007_enginetype_yaml_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='yaml_configuration',
            field=models.CharField(max_length=1000),
        ),
    ]
