# Generated by Django 3.0.7 on 2020-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0008_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='short_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='short_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
