# Generated by Django 3.0.7 on 2020-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0009_auto_20200715_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='yaml_configuration',
            field=models.TextField(max_length=1000),
        ),
    ]
