# Generated by Django 3.0.7 on 2020-07-15 18:26

from django.db import migrations
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0010_auto_20200715_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='yaml_configuration',
            field=yamlfield.fields.YAMLField(),
        ),
    ]
