# Generated by Django 3.0.7 on 2020-07-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0011_auto_20200715_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='yaml_configuration',
            field=models.TextField(),
        ),
    ]
