# Generated by Django 3.1.6 on 2021-04-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('domain_description', models.TextField()),
                ('insert_date', models.DateTimeField()),
                ('last_scan_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
