# Generated by Django 3.2.4 on 2021-10-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whois',
            new_name='WhoisDetail',
        ),
    ]
