# Generated by Django 3.2.4 on 2021-10-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ip_address_cidr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
