# Generated by Django 3.2.23 on 2026-04-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('scanEngine', '0004_opsec'),
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_monitored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_monitored',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='monitor_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanEngine.enginetype'),
        ),
        migrations.AddField(
            model_name='domain',
            name='monitor_frequency',
            field=models.IntegerField(default=24, help_text='Monitoring frequency in hours'),
        ),
        migrations.AddField(
            model_name='domain',
            name='monitor_periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='domain',
            name='monitor_scan_scope',
            field=models.CharField(choices=[('targeted', 'Targeted Scan'), ('full', 'Full Scan')], default='targeted', max_length=20),
        ),
    ]
