# Generated by Django 3.2.23 on 2026-04-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_auto_20260425_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='monitor_frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
    ]
