# Generated by Django 3.2.4 on 2021-10-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_rename_whois_whoisdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameServerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('ns', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.nameserverhistory')),
            ],
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='ns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.nameserver'),
        ),
    ]
