# Generated by Django 3.1.6 on 2021-06-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_auto_20210502_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='domain_name',
            new_name='name',
        ),
    ]
