# Generated by Django 3.2.4 on 2021-10-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0002_domain_ip_address_cidr'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='whois',
            field=models.TextField(blank=True, null=True),
        ),
    ]
