# Generated by Django 3.2.4 on 2021-10-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0003_auto_20211030_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaininfo',
            name='ns',
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='nameserver_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.nameserverhistory'),
        ),
        migrations.DeleteModel(
            name='NameServer',
        ),
    ]
