# Generated by Django 3.2.4 on 2022-04-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0003_auto_20220406_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateddomain',
            name='assocation_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='associateddomain',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nameserverhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nsrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrantinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whoisdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
