# Generated by Django 3.2.4 on 2021-06-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0004_auto_20210607_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
