# Generated by Django 3.2.4 on 2021-10-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0004_auto_20211030_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaininfo',
            name='nameserver_history',
        ),
        migrations.AddField(
            model_name='nameserverhistory',
            name='domain_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domaininfo'),
        ),
    ]
