# Generated by Django 3.2.4 on 2022-04-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0004_auto_20220406_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associateddomain',
            old_name='assocation_by',
            new_name='association_by',
        ),
    ]
