# Generated by Django 3.2.4 on 2021-10-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0005_auto_20211030_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nameserverhistory',
            old_name='ns',
            new_name='server',
        ),
        migrations.RemoveField(
            model_name='nameserverhistory',
            name='domain_info',
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='nameserver_history',
            field=models.ManyToManyField(to='targetApp.NameServerHistory'),
        ),
    ]
