# Generated by Django 3.2.4 on 2021-07-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0005_alter_domain_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('targets', models.ManyToManyField(related_name='targets', to='targetApp.Domain')),
            ],
        ),
    ]
