# Generated by Django 3.2.4 on 2022-04-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0005_rename_assocation_by_associateddomain_association_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associateddomain',
            name='association_by',
        ),
    ]
