# Generated by Django 3.2.4 on 2021-07-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0006_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='ok', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
