# Generated by Django 3.2.4 on 2022-04-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0007_auto_20220406_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTLD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registrantinfo',
            name='associated_domains',
            field=models.ManyToManyField(blank=True, to='targetApp.AssociatedDomain'),
        ),
        migrations.AddField(
            model_name='registrantinfo',
            name='related_tld',
            field=models.ManyToManyField(blank=True, to='targetApp.RelatedTLD'),
        ),
    ]
