# Generated by Django 3.2.4 on 2021-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0007_auto_20211030_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('preference', models.CharField(blank=True, max_length=5, null=True)),
                ('ttl', models.CharField(blank=True, max_length=10, null=True)),
                ('ns_class', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
