# Generated by Django 3.2.4 on 2022-04-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0008_auto_20220413_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrantinfo',
            old_name='related_tld',
            new_name='related_tlds',
        ),
    ]
