# Generated by Django 3.2.4 on 2021-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0008_nsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='nameserver_record',
            field=models.ManyToManyField(to='targetApp.NSRecord'),
        ),
    ]
