# Generated by Django 3.2.4 on 2022-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0009_rename_related_tld_registrantinfo_related_tlds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrantinfo',
            name='associated_domains',
        ),
        migrations.RemoveField(
            model_name='registrantinfo',
            name='email_association_href',
        ),
        migrations.RemoveField(
            model_name='registrantinfo',
            name='organization_association_href',
        ),
        migrations.RemoveField(
            model_name='registrantinfo',
            name='related_tlds',
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='associated_domains',
            field=models.ManyToManyField(blank=True, to='targetApp.AssociatedDomain'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='email_association_href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='organization_association_href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='related_tlds',
            field=models.ManyToManyField(blank=True, to='targetApp.RelatedTLD'),
        ),
    ]
