# Generated by Django 3.2.4 on 2022-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0010_auto_20220413_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='date_expiration',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
