# Generated by Django 3.2.4 on 2022-06-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0011_domaininfo_date_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DomainCity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DomainCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DomainEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DomainFax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DomainPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DomainRegisterName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DomainRegisterOrganization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DomainState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DomainZipCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NameServers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='whoisdetail',
            name='registrant',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='domain_age',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='email_association_href',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='geolocation_iso',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='nameserver_history',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='nameserver_record',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='organization_association_href',
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='whois',
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='raw_text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='NameServerHistory',
        ),
        migrations.DeleteModel(
            name='NSRecord',
        ),
        migrations.DeleteModel(
            name='RegistrantInfo',
        ),
        migrations.DeleteModel(
            name='WhoisDetail',
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_address',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainAddress'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_city',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainCity'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_country',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainCountry'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_email',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainEmail'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_fax',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainFax'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_name',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainRegisterName'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_organization',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainRegisterOrganization'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_phone',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainPhone'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_state',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainState'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrant_zip_code',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainZipCode'),
        ),
    ]
