# Generated by Django 3.2.4 on 2021-07-08 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0011_alter_organization_insert_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='targets',
        ),
        migrations.AddField(
            model_name='organization',
            name='domains',
            field=models.ManyToManyField(related_name='domains', to='targetApp.Domain'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 4, 53, 53, 301182, tzinfo=utc)),
        ),
    ]
