# Generated by Django 3.2.4 on 2022-06-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0013_auto_20220615_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRegistrar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DomainRegistrarID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='registrar',
            field=models.ManyToManyField(blank=True, to='targetApp.DomainRegisterName'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='admin_id',
            field=models.ManyToManyField(blank=True, related_name='admin_id', to='targetApp.DomainRegistrarID'),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='tech_id',
            field=models.ManyToManyField(blank=True, related_name='tech_id', to='targetApp.DomainRegistrarID'),
        ),
    ]
