# Generated by Django 3.2.4 on 2022-06-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0014_auto_20220615_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='dnssec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='raw_text',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
    ]
