# Generated by Django 3.2.4 on 2022-06-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0016_alter_domaininfo_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
