# Generated by Django 3.2.4 on 2022-06-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0020_auto_20220617_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
