# Generated by Django 3.2.4 on 2022-08-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0023_auto_20220617_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='insert_date',
            field=models.DateTimeField(null=True),
        ),
    ]
