# Generated by Django 3.2.4 on 2022-09-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0024_alter_domain_insert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='request_headers',
            field=models.JSONField(null=True),
        ),
    ]
