# Generated by Django 3.2.4 on 2023-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0029_auto_20230412_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='geolocation_iso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
