# Generated by Django 3.2.4 on 2021-08-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0031_alter_organization_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='h1_team_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
