# Generated by Django 3.2.4 on 2023-04-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0031_auto_20230412_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='whois_server',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
