# Generated by Django 3.2.4 on 2023-04-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0032_domaininfo_whois_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameserver',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
