# Generated by Django 3.2.4 on 2023-04-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0033_alter_nameserver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='similar_domains',
            field=models.ManyToManyField(blank=True, related_name='similar_domains', to='targetApp.AssociatedDomain'),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='associated_domains',
            field=models.ManyToManyField(blank=True, related_name='associated_domains', to='targetApp.AssociatedDomain'),
        ),
    ]
