# Generated by Django 3.2.4 on 2023-04-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0034_auto_20230412_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateddomain',
            name='created_on',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associateddomain',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
