# Generated by Django 3.2.4 on 2023-06-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_project_slug'),
        ('targetApp', '0038_rename_associateddomain_relateddomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
