apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest # Using the image from docker-compose
        ports:
        - containerPort: 11434 # Port used inside the container
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama # Same mount path as in docker-compose
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
