# Generated by Django 3.1.6 on 2021-06-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginetype',
            name='osint',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
