# Generated by Django 3.2.4 on 2022-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedexternaltool',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='installedexternaltool',
            name='github_clone_path',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='installedexternaltool',
            name='github_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='installedexternaltool',
            name='license_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
