# Generated by Django 3.2.23 on 2024-09-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerone',
            name='send_report',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
