# Generated by Django 3.2.4 on 2022-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0002_auto_20220526_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginetype',
            name='waf_detection',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
