# Generated by Django 3.2.4 on 2021-12-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0002_installedexternaltools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstalledExternalTools',
            new_name='InstalledExternalTool',
        ),
    ]
