# Generated by Django 3.2.4 on 2021-06-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_auto_20210626_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginetype',
            name='screenshot',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
