# Generated by Django 3.2.4 on 2022-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_enginetype_waf_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='dir_file_fuzz',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='fetch_url',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='port_scan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='subdomain_discovery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='enginetype',
            name='http_crawl',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
