# Generated by Django 3.2.4 on 2022-08-16 09:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_enginetype_waf_detection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginetype',
            name='dir_file_fuzz',
        ),
        migrations.RemoveField(
            model_name='enginetype',
            name='fetch_url',
        ),
        migrations.RemoveField(
            model_name='enginetype',
            name='osint',
        ),
        migrations.RemoveField(
            model_name='enginetype',
            name='port_scan',
        ),
        migrations.RemoveField(
            model_name='enginetype',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='enginetype',
            name='subdomain_discovery',
        ),
        migrations.RemoveField(
            model_name='enginetype',
            name='vulnerability_scan',
        ),
        migrations.RemoveField(
            model_name='enginetype',
            name='waf_detection',
        ),
    ]
