# Generated by Django 3.2.23 on 2026-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_vulnerabilityreportsetting_enable_llm_report_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpSec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enable_opsec', models.BooleanField(default=False)),
                ('enable_random_ua', models.BooleanField(default=True)),
                ('enable_rate_limit', models.BooleanField(default=False)),
                ('max_rps', models.IntegerField(default=10)),
                ('enable_delay', models.BooleanField(default=False)),
                ('delay_ms', models.IntegerField(default=100)),
                ('enable_jitter', models.BooleanField(default=False)),
                ('jitter_percent', models.IntegerField(default=10)),
                ('enable_waf_bypass', models.BooleanField(default=False)),
                ('enable_ja3_randomization', models.BooleanField(default=False)),
                ('http_protocol', models.CharField(default='http2', max_length=10)),
                ('custom_dns_servers', models.TextField(blank=True, null=True)),
                ('enable_metadata_stripping', models.BooleanField(default=False)),
            ],
        ),
    ]
