# Generated by Django 3.2.4 on 2021-12-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0003_rename_installedexternaltools_installedexternaltool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installedexternaltool',
            old_name='tool_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='installedexternaltool',
            old_name='tool_name',
            new_name='name',
        ),
    ]
