# Generated by Django 3.2.4 on 2022-09-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0004_auto_20220816_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_scan_tracebacks',
            field=models.BooleanField(default=True),
        ),
    ]
