# Generated by Django 3.2.4 on 2022-08-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0004_auto_20220804_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginetype',
            name='http_crawl',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
