# Generated by Django 3.2.4 on 2021-07-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0004_enginetype_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_to_slack', models.BooleanField(default=False)),
                ('send_to_discord', models.BooleanField(default=False)),
                ('send_to_telegram', models.BooleanField(default=False)),
                ('slack_hook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('discord_hook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_bot_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('send_scan_status_notif', models.BooleanField(default=False)),
                ('send_interesting_notif', models.BooleanField(default=False)),
                ('send_vuln_notif', models.BooleanField(default=False)),
                ('send_new_subdomain_notif', models.BooleanField(default=False)),
            ],
        ),
    ]
