# Generated by Django 3.2.4 on 2021-12-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0005_installedexternaltool_update_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedexternaltool',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
