# Generated by Django 3.2.4 on 2021-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0006_auto_20210713_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='send_scan_output_file',
            field=models.BooleanField(default=True),
        ),
    ]
