# Generated by Django 3.2.4 on 2021-12-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0007_installedexternaltool_is_subdomain_gathering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installedexternaltool',
            name='active_passive',
        ),
    ]
