# Generated by Django 3.2.4 on 2021-07-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0007_notificationmodel_send_scan_output_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationModel',
            new_name='Notification',
        ),
    ]
