# Generated by Django 3.2.4 on 2021-07-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0008_rename_notificationmodel_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='send_new_subdomain_notif',
            new_name='send_subdomain_changes_notif',
        ),
    ]
