# Generated by Django 3.2.4 on 2021-12-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0008_remove_installedexternaltool_active_passive'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedexternaltool',
            name='install_command',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installedexternaltool',
            name='update_command',
            field=models.CharField(max_length=200),
        ),
    ]
