# Generated by Django 3.2.4 on 2021-12-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0009_auto_20211218_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedexternaltool',
            name='update_command',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='installedexternaltool',
            name='version_lookup_command',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='installedexternaltool',
            name='version_match_regex',
            field=models.CharField(blank=True, default='v(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)', max_length=100, null=True),
        ),
    ]
