# Generated by Django 3.2.4 on 2021-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0009_rename_send_new_subdomain_notif_notification_send_subdomain_changes_notif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('use_proxy', models.BooleanField(default=False)),
                ('proxies', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
