# Generated by Django 3.2.4 on 2021-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0010_auto_20211218_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedexternaltool',
            name='version_match_regex',
            field=models.CharField(blank=True, default='[vV]*(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)', max_length=100, null=True),
        ),
    ]
