# Generated by Django 3.2.4 on 2021-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0010_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackerone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('send_critical', models.BooleanField(default=True)),
                ('send_high', models.BooleanField(default=True)),
                ('send_medium', models.BooleanField(default=False)),
                ('report_template', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
