# Generated by Django 3.2.4 on 2021-12-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0011_alter_installedexternaltool_version_match_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedexternaltool',
            name='subdomain_extra_command',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='installedexternaltool',
            name='subdomain_output_command',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='installedexternaltool',
            name='subdomain_proxy_command',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='installedexternaltool',
            name='subdomain_target_command',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
