# Generated by Django 3.2.4 on 2021-12-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0012_auto_20211221_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedexternaltool',
            name='license_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installedexternaltool',
            name='subdomain_extra_command',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installedexternaltool',
            name='version_lookup_command',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
