# Generated by Django 3.2.4 on 2021-10-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0013_rename_vulnerabilityreport_vulnerabilityreportsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilityreportsettings',
            name='methodology_description',
        ),
        migrations.RemoveField(
            model_name='vulnerabilityreportsettings',
            name='show_methodology',
        ),
    ]
