# Generated by Django 3.2.4 on 2021-12-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0013_auto_20211221_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installedexternaltool',
            name='category',
        ),
    ]
