# Generated by Django 3.2.4 on 2021-10-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0019_vulnerabilityreportsettings_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilityreportsettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#FFB74D', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilityreportsettings',
            name='secondary_color',
            field=models.CharField(blank=True, default='#212121', max_length=10, null=True),
        ),
    ]
