export const STORAGE_KEYS = {
	activeProjectSlug: 'rengine:projects:activeSlug',
	launchLastEngine: 'rengine:launch:lastEngine',
	toolboxLastTool: 'rengine:toolbox:lastTool',
	launchLastContext: 'rengine:launch:lastContext',
	targetViews: 'rengine:targets:views',
	engineLensTargetType: 'rengine:engine:lensTargetType',
	engineSidePane: 'rengine:engine:sidePane',
	engineSplit: 'rengine:engine:split',
	engineSideTab: 'rengine:engine:sideTab',
	contextSplit: 'rengine:context:split',
	activityPinned: 'rengine:activity:pinned',
	activityGrouping: 'rengine:activity:grouping',
	webAssetsView: 'rengine:webassets:view',
	webAssetsColumns: 'rengine:webassets:columns',
	webAssetsDensity: 'rengine:webassets:density',
	webAssetsPageSize: 'rengine:webassets:pageSize',
	webAssetsRecentQueries: 'rengine:webassets:recentQueries',
	ipsColumns: 'rengine:ips:columns',
	ipsRecentQueries: 'rengine:ips:recentQueries',
	ipsDensity: 'rengine:ips:density',
	ipsPageSize: 'rengine:ips:pageSize',
	servicesColumns: 'rengine:services:columns',
	servicesRecentQueries: 'rengine:services:recentQueries',
	servicesDensity: 'rengine:services:density',
	servicesPageSize: 'rengine:services:pageSize',
	softwareColumns: 'rengine:software:columns',
	softwareRecentQueries: 'rengine:software:recentQueries',
	softwareDensity: 'rengine:software:density',
	softwarePageSize: 'rengine:software:pageSize',
	secretRecentQueries: 'rengine:secrets:recentQueries',
	secretPageSize: 'rengine:secrets:pageSize',
	endpointsColumns: 'rengine:endpoints:columns',
	endpointsRecentQueries: 'rengine:endpoints:recentQueries',
	endpointsDensity: 'rengine:endpoints:density',
	endpointsPageSize: 'rengine:endpoints:pageSize',
	endpointsView: 'rengine:endpoints:view',
	endpointsHideRootOnly: 'rengine:endpoints:hideRootOnly',
	endpointsHideStatic: 'rengine:endpoints:hideStatic',
	endpointsOutlineColumns: 'rengine:endpoints:outlineColumns',
	endpointsHostColumns: 'rengine:endpoints:hostColumns',
	endpointsExpanded: 'rengine:endpoints:expanded',
	vulnsColumns: 'rengine:vulns:columns',
	vulnsRecentQueries: 'rengine:vulns:recentQueries',
	vulnsDensity: 'rengine:vulns:density',
	vulnsPageSize: 'rengine:vulns:pageSize',
	vulnsView: 'rengine:vulns:view',
	launchLastPlan: 'rengine:launch:lastPlan',
	bountyConnectDismissed: 'rengine:bountyhub:connectDismissed',
	dashboardWidgets: 'rengine:dashboard:widgets',
	scanTabs: 'rengine:scan:tabs',
	paletteRecents: 'rengine:palette:recents'
} as const;

// Keys that were once stored outside the `rengine:` namespace. `readRaw` in
// `$lib/utilities/storage` still reads the old name and moves the value over,
// so a returning viewer keeps the active project and saved target views.
export const LEGACY_STORAGE_KEYS: Readonly<Record<string, string>> = {
	[STORAGE_KEYS.activeProjectSlug]: 'activeProjectSlug',
	[STORAGE_KEYS.targetViews]: 'targets:views'
};
