export const STORAGE_KEYS = {
	activeProjectSlug: 'activeProjectSlug',
	launchLastEngine: 'rengine:launch:lastEngine',
	launchLastContext: 'rengine:launch:lastContext',
	targetViews: 'targets:views',
	engineLensTargetType: 'rengine:engine:lensTargetType',
	engineSidePane: 'rengine:engine:sidePane',
	engineSplit: 'rengine:engine:split',
	engineSideTab: 'rengine:engine:sideTab',
	contextSplit: 'rengine:context:split',
	activityPinned: 'rengine:activity:pinned',
	activityGrouping: 'rengine:activity:grouping',
	webAssetsView: 'rengine:webassets:view',
	webAssetsColumns: 'rengine:webassets:columns',
	webAssetsDensity: 'rengine:webassets:density',
	webAssetsPageSize: 'rengine:webassets:pageSize',
	webAssetsRecentQueries: 'rengine:webassets:recentQueries',
	ipsColumns: 'rengine:ips:columns',
	ipsRecentQueries: 'rengine:ips:recentQueries',
	ipsDensity: 'rengine:ips:density',
	ipsPageSize: 'rengine:ips:pageSize'
} as const;
